//
//  ScannerGraphics.h
//  DianDian
//
//  Created by Sam Lau on 10/6/15.
//  Copyright (c) 2015 DianDian. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface ScannerGraphics : NSObject

// Drawing Methods
+ (void)drawScannerRectangleWithFrame: (CGRect)frame;

// Rect of Interest
+ (CGRect)rectOfInterest:(CGRect)frame;
+ (CGRect)scanAreaFrame:(CGRect)frame;

@end
